apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: tmp
spec:
  selector:
    matchLabels:
      app: tmp
  replicas: 3
  template:
    metadata:
      labels:
        app: tmp
    spec:
      containers:
      - name: tmp
        image: ecr/image:tag
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080
