apiVersion: v1
kind: Service
metadata:
  name: pullrapiserver
  labels:
    app: pullrapiserver
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30100
  selector:
    app: pullrapiserver
