sudo: required
env:
- DIRNAME_OLD=.
- BUILT=.
services:
- docker
script: 
- echo "range ${TRAVIS_COMMIT_RANGE}"
- git diff --name-only $TRAVIS_COMMIT_RANGE | while read line; do
    DIRNAME=`dirname ${line}`;
    if [[ "$DIRNAME" == "$DIRNAME_OLD" ]]; then
      echo "current same as old dir, skip (${DIRNAME} = ${DIRNAME_OLD})";
    else
      echo "built = ${BUILT}"
      if [[ $BUILT == *"${DIRNAME}"* ]]; then
        echo "${DIRNAME} already built, skip";
      else
        echo "build ${DIRNAME}/Makefile";
        BUILT=`echo "${BUILT};${DIRNAME}"`;
      fi;
    fi;
    DIRNAME_OLD=$DIRNAME;
  done
