sudo: required
services:
- docker
script: 
- echo "range ${TRAVIS_COMMIT_RANGE}"
- git diff --name-only c5184738f030...5a8412e3e5d8 | while read line; do
    DIRNAME=`dirname ${line}`;
    echo "build ${DIRNAME}/Makefile";
  done
