sudo: required
services:
- docker
script: 
- echo "range ${TRAVIS_COMMIT_RANGE}"
- git diff --name-only $TRAVIS_COMMIT_RANGE | while read line; do
    DIRNAME=`dirname ${line}`;
    echo "build ${DIRNAME}/Makefile";
  done
