version: "3"

services:
  docker-registry-external:
    environment:
      - REGISTRY_AUTH_TOKEN_REALM='https://reg.pullr.dev/tokensrv/auth'
  pullr-mongodb:
    ports:
      - 27017:27017
  pullr-rabbitmq:
    ports:
      - 5671:5671
      - 5672:5672
  pullr-apisrv:
    build:
      context: .
      dockerfile: cmd/apisrv/Dockerfile
    ports:
      - 9000:8080
  pullr-ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    volumes:
      - "./ui/dist:/www:ro"
#  pullr-proxy:
#    command:
#      - --docker
#      - --entryPoints='Name:https TLS:/certs/dev.crt,/certs/dev.key'
