version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    command: --auth --bind_ip_all
    environment:
    - MONGO_DATA_DIR=/data/db
    volumes:
    - "/var/tmp/pullr/mongodb:/data/db"
    ports:
    - "27017:27017"
  tokenserver:
    container_name: tokenserver
    image: cesanta/docker_auth:1
    command: --v=3 --alsologtostderr /config/auth_config.yml
    ports:
    - "5001:5001"
    volumes:
    - "./certs:/certs:ro"
    - "./registry/tokenserver:/config:ro"
    depends_on:
    - mongodb
  apiserver:
    container_name: apiserver
    image: pullrapiserver
    ports:
    - "8080:8080"
  registry:
    container_name: registry2
    image: registry:2
    ports:
    - "5000:5000"
    volumes:
    - "./certs:/certs:ro"
    - "./registry:/etc/docker/registry:ro"
    - "/var/tmp/pullr/registry:/var/lib/registry:rw"
    depends_on:
    - tokenserver
    - apiserver
  mqueue:
    container_name: mqueue
    image: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
