version: '3'
networks:
  pullr:
services:
  pullr-mongodb:
    container_name: pullr-mongodb
    image: mongo:latest
    command: --auth --bind_ip_all
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - "./tmp/mongodb:/data/db"
    networks:
      pullr:

  pullr-rabbitmq:
    container_name: pullr-rabitmq
    image: rabbitmq
    networks:
      pullr:

  docker-registry-tokensrv:
    container_name: docker-registry-tokensrv
    image: mobingilabs/docker_auth:1.11
    command: ["--v=3", "--alsologtostderr", "/conf/docker_auth.yml", "AUTH"]
    environment:
      - AUTH_MONGOAUTH_DIALINFO_USERNAME=pullr
      - AUTH_MONGOAUTH_DIALINFO_PASSWORD=pullrpass
      - AUTH_MONGOAUTH_DIALINFO_PASSWORDFILE=""
    volumes:
      - "./conf:/conf:ro"
      - "./certs:/certs:ro"
    networks:
      pullr:
    depends_on:
      - pullr-mongodb


  docker-registry-internal:
    container_name: docker-registry-internal
    image: registry:2
    environment:
      - REGISTRY_HTTP_ADDR=':5050'
      - REGISTRY_AUTH_TOKEN_REALM='https://docker-registry-tokensrv:5001/auth'
    volumes:
      - "./certs:/certs:ro"
      - "./conf/docker_registry.yml:/etc/docker/registry/config.yml:ro"
      - "/var/tmp/pullr/registry:/var/lib/registry:rw"
    depends_on:
      - docker-registry-tokensrv
    networks:
      pullr:
        aliases:
          - docker-registry

  docker-registry-external:
    container_name: docker-registry-external
    image: registry:2
    volumes:
      - "./certs:/certs:ro"
      - "./conf/docker_registry.yml:/etc/docker/registry/config.yml:ro"
      - "/var/tmp/pullr/registry:/var/lib/registry:rw"
    depends_on:
      - docker-registry-tokensrv
    networks:
      pullr:
        aliases:
          - docker-registry

  pullr-proxy:
    container_name: pullr-proxy
    image: nginx:1.12.2
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./conf/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./certs:/certs:ro"
    networks:
      pullr:
    depends_on:
      - docker-registry-external
      - docker-registry-tokensrv
      - pullr-ui
      - pullr-apisrv

  pullr-ui:
    container_name: pullr-ui
    image: mobingilabs/pullr-ui:localdev
    networks:
      pullr:

  pullr-apisrv:
    container_name: pullr-apisrv
    image: mobingilabs/pullr-apisrv:localdev
    command: ["serve"]
    networks:
      pullr:
    volumes:
      - "./certs:/certs:ro"
    environment:
      - PULLR_OAUTH_CLIENTS_GITHUB_ID=$GITHUBID
      - PULLR_OAUTH_CLIENTS_GITHUB_SECRET=$GITHUBSECRET
    depends_on:
      - pullr-mongodb
      - pullr-rabbitmq

  pullr-buildctl:
    container_name: pullr-buildctl
    image: mobingilabs/pullr-buildctl:localdev
    command: ["listen"]
    networks:
      pullr:
    environment:
      - PULLR_BUILD_CLONEDIR=./tmp/src
      - PULLR_REGISTRY_USERNAME=admin
      - PULLR_REGISTRY_PASSWORD=admin
      - PULLR_REGISTRY_URL=https://docker-registry:5050
      - DOCKER_HOST=tcp://pullr-dind:2375
    depends_on:
      - pullr-mongodb
      - pullr-rabbitmq
      - pullr-dind
      - docker-registry-internal
  pullr-dind:
    container_name: pullr-dind
    image: docker:17.12.0-dind
    networks:
      pullr:
    depends_on:
      - docker-registry-internal
    command:
      - "--insecure-registry"
      - "docker-registry:5050"
    volumes:
      - "./tmp/dind:/var/lib/docker:rw"
    privileged: true
