version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    command: --auth --bind_ip_all
    environment:
    - MONGO_DATA_DIR=/data/db
    volumes:
    - "/Users/umurgdk/Work/mobingi/pullr/mongodb:/data/db"
    ports:
    - "27017:27017"
  tokenserver:
    container_name: tokenserver
    image: cesanta/docker_auth:1
    command: --v=3 --alsologtostderr /config/auth_config.yml
    ports:
    - "5001:5001"
    volumes:
    - "./certs:/certs:ro"
    - "./registry/tokenserver:/config:ro"
    depends_on:
    - mongodb
  apisrv:
    container_name: apisrv
    image: pullr-apisrv:localdev
    command: serve
    volumes:
    - "./certs:/certs:ro"
    environment:
    - PORT=8080
    - AUTHSTORAGE=http://mongodb:27017
    - STORAGE=http://mongodb:27017
    - REDIRECT_WHITELIST=http://188.166.71.32
    - SERVER_URL=http://188.166.71.32
    - FRONTEND_URL=http://188.166.71.32
    - GITHUB_CLIENT=3d80f42bb8bed7caa9de
    - GITGUB_SECRET=4f8ce81cd83fee2c1ed7bef0a70f31bf3a46548c
    - CERTS=/certs
    ports:
    - "8080:8080"
    depends_on:
    - mongodb
  eventsrv:
    container_name: eventsrv
    image: pullr-eventsrv:localdev
    command: serve
    depends_on:
    - mongodb
    - mqueue
  buildctl:
    container_name: buildctl
    image: pullr-buildctl:localdev
    volumes:
    - ./tmp/src:/data/src
    environment:
    - AMQP=amqp://mqueue:5672
    - STORAGE=http://mongodb:27017
    - CLONE_DIR=/data/src
    - REG_USERNAME=$REG_USERNAME
    - REG_PASSWORD=$REG_PASSWORD
    - REGISTRY=http://registry:5000
    depends_on:
    - registry
    - mqueue
    - mongodb
  registry:
    container_name: registry2
    image: registry:2
    ports:
    - "5000:5000"
    volumes:
    - "./certs:/certs:ro"
    - "./registry:/etc/docker/registry:ro"
    - "/var/tmp/pullr/registry:/var/lib/registry:rw"
    depends_on:
    - tokenserver
  mqueue:
    container_name: mqueue
    image: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
