version: "3"

services:
  docker-registry-external:
    environment:
      - REGISTRY_AUTH_TOKEN_REALM='https://reg.pullr.dev/tokensrv/auth'
  pullr-apisrv:
    build:
      context: .
      dockerfile: cmd/apisrv/Dockerfile
  pullr-buildctl:
    build:
      context: .
      dockerfile: cmd/buildctl/Dockerfile
  pullr-ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    volumes:
      - "./ui/dist:/www:ro"
#  pullr-proxy:
#    command:
#      - --docker
#      - --entryPoints='Name:https TLS:/certs/dev.crt,/certs/dev.key'
