# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
[[constraint]]
  name = "github.com/jinzhu/copier"
  revision = "7e38e58719c33e0d44d585c4ab477a30f8cb82dd"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  name = "gopkg.in/mgo.v2"
  branch = "v2"

[[constraint]]
  name = "github.com/streadway/amqp"
  revision = "8e4aba63da9fc5571e01c6a45dc809a58cbc5a68"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.1.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/facebookgo/grace"
  revision = "4afe952a37a495ae4ac0c1d4ce5f66e91058d149"

[[constraint]]
  name = "github.com/docker/machine"
  version = "0.14.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.54"
