apiVersion: apps/v1
kind: Deployment
metadata:
  name: pullr-apisrv
  labels:
    app: pullr
    tier: backend
    impl: apisrv
spec:
  selector:
    matchLabels:
      app: pullr
      tier: backend
      impl: apisrv
  replicas: 2
  template:
    metadata:
      labels:
        app: pullr
        tier: backend
        impl: apisrv
    spec:
      containers:
        - name: apisrv
          image: mobingilabs/pullr-apisrv:localdev
          args: ['-c', '/conf/pullr.yml']
          resources:
            requests:
              cpu: 100m
              memory: 100Mi

          ports:
            - containerPort: 8080

          env:
            - name: PULLR_CONF_FILE
              value: /conf/apisrv.yml

            - name: PULLR_OAUTH_GITHUB_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: pullr
                  key: githubid
            - name: PULLR_OAUTH_GITHUB_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: pullr
                  key: githubsecret

          volumeMounts:
            - name: secrets
              mountPath: /certs
            - name: conf
              mountPath: /conf

      volumes:
        - name: secrets
          secret:
            secretName: pullr

        - name: conf
          configMap:
            name: pullr

