apiVersion: v1
kind: Service
metadata:
  name: pullr-mongodb
  labels:
    app: pullr
    tier: storage
    impl: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: pullr
    tier: storage
    impl: mongodb
