apiVersion: v1
kind: Service
metadata:
  name: pullr-proxy
  labels:
    app: pullr
    tier: frontend
    impl: proxy
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: pullr
    impl: proxy
