apiVersion: v1
kind: Service
metadata:
  name: pullr-rabbitmq
  labels:
    app: pullr
    tier: jobq
    impl: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    app: pullr
    tier: jobq
    impl: rabbitmq
