apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: pullr
    tier: registry
spec:
  ports:
  - name: tokensrv
    port: 5001
  - name: external-registry
    port: 5000
  - name: internal-registry
    port: 5050
  selector:
    app: pullr
    tier: registry
