apiVersion: v1
kind: Service
metadata:
  name: pullr-ui
  labels:
    app: pullr
    tier: frontend
    impl: ui
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: pullr
    tier: frontend
    impl: ui
